### ISSUE TITLE
General cert name

### ISSUE THREAD

**Issue by whiskey** [noodlewerk/NWPusher#18] opened 2015-12-18 15:58 UTC
Apple recently [changed their APNS handling](https://developer.apple.com/news/?id=12172015b) and new certificates are named "Apple Push Services" instead of "Apple Production IOS Push Services". When I now try to import one of these Pusher refuses to import them.

**Comment by aleufms** [comment] 2015-12-18 16:12
+1

**Comment by leonardvandriel** [comment] 2015-12-20 04:10
I added the 'Simplified' certificate type in commit 49ca3dd. @whiskey could you see if that fixes the issue? Thanks.

**Comment by whiskey** [comment] 2015-12-20 10:12
The new certificates can now be selected but on connection I get a SSL handshake error:
`[10:08:24.081366 Pusher NWAppDelegate.m:334] [warn] Unable to connect: SSL handshake failed (-9806)`
Let me know if you need further testing or review.

**Comment by leonardvandriel** [comment] 2015-12-21 00:07
Thanks for checking that. It looks like APNS handles connections differently for this new kind of certificate. The SSL handshake fails because of either the connection is reset (`ECONNRESET`) or a broken pipe (`EPIPE`), see `NWSSLConnection.m` for more details. I currently don't have such a certificate to further investigate the matter, but will get back to you once I do.

**Comment by leonardvandriel** [comment] 2015-12-21 00:11
For the sake of better error reporting, I added this `errSSLClosedAbort` (-9806) error in commit 504ab4d.

**Comment by yuriypavlyshak** [comment] 2015-12-21 12:44
I had the same issue but the new certificate type works for me in version 0.6.4.

**Comment by hemang-azilen** [comment] 2016-01-04 05:12
@leonardvandriel, I'm trying to use production certificate to send push notification but its not showing up so I couldn't select it, and even tried importing .p12 wouldn't help.

**Comment by hemang-azilen** [comment] 2016-01-04 09:02
any plan to release new build for Apple's updates? @leonardvandriel

**Comment by leonardvandriel** [comment] 2016-01-04 09:20
@hemang-azilen, which particular Apple's update are you referring to? I did a small update (0.6.4) that should add some support for the new certificates. I'm currently not planning to add support for the HTTP/2 APNS.

**Comment by hemang-azilen** [comment] 2016-01-04 09:25
@leonardvandriel , I'm referring to this, https://developer.apple.com/news/?id=12172015b

Please have a look.

**Comment by leonardvandriel** [comment] 2016-01-04 09:27
Thanks, I'm aware of this. This update consists of a set of changes. Are you referring to the Simplified Certificate Handling?

**Comment by hemang-azilen** [comment] 2016-01-04 09:32
Yes, may be. NWPusher was working fine before with either development or production certificate. Now its only working with Development.

**Comment by leonardvandriel** [comment] 2016-01-04 11:26
Could you describe how it's not working? Maybe an error message or code.

**Comment by leonardvandriel** [comment] 2016-01-04 11:29
I see, you say it's not showing up. This is probably because you're using certificates that can be used for both production and development, which aren't showing up as such anymore. There's a pull request that deals with this (https://github.com/noodlewerk/NWPusher/pull/11). I'm looking into merging this. In the mean time you could give that a try.

**Comment by hemang-azilen** [comment] 2016-01-04 11:41
![screen shot 2016-01-04 at 5 09 38 pm](https://cloud.githubusercontent.com/assets/16533664/12088990/0d044586-b306-11e5-8600-3fc2152cad7a.png)

I'm getting following message inside NWPusher when tried to import .p12 from a production certificate (which I'd created after Apple changed their way of creating production certificates).

**Comment by 666tos** [comment] 2016-01-05 13:03
@leonardvandriel should I update my pull request to be compatible with most recent codebase?

**Comment by leonardvandriel** [comment] 2016-01-08 00:12
Thanks all for your patience. I've merged @666tos pull request and support for both production and sandbox on simplified certificates is now available.

@666tos Thanks for picking this up.
@hemang-azilen Can you verify the issue is now resolved?

**Comment by hemang-azilen** [comment] 2016-01-08 05:06
@leonardvandriel, that's great, thanks for this! Its working now! Bingo!! :+1:

**Closed** 2016-01-08 17:43 UTC
